src/Entity/Suite.php
<?php

namespace App\Entity;

use App\Repository\SuiteRepository;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: SuiteRepository::class)]
class Suite
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column(type: 'integer')]
    private $id;

    #[ORM\Column(type: 'string', length: 80)]
    private $nom;

    #[ORM\Column(type: 'integer')]
    private $prix;

    #[ORM\Column(type: 'string', length: 100)]
    private $url_booking;

    #[ORM\ManyToOne(targetEntity: Etablissement::class, inversedBy: 'suites')]
    /* #[ORM\JoinColumn(nullable: false)] */
    private $id_hotel;

    #[ORM\Column(type: 'text')]
    private $description;

    #[ORM\Column(type: 'string', length: 255)]
    private $slug;

    #[ORM\Column(type: 'string', length: 255)]
    private $photo_principale;

    #[ORM\Column(type: 'string', length: 255)]
    private $photo_deux;

    #[ORM\Column(type: 'string', length: 255)]
    private $photo_3;

    #[ORM\Column(type: 'string', length: 95)]
    private $description_intro;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNom(): ?string
    {
        return $this->nom;
    }

    public function setNom(string $nom): self
    {
        $this->nom = $nom;

        return $this;
    }

    public function getPrix(): ?int
    {
        return $this->prix;
    }

    public function setPrix(int $prix): self
    {
        $this->prix = $prix;

        return $this;
    }

    public function getUrlBooking(): ?string
    {
        return $this->url_booking;
    }

    public function setUrlBooking(string $url_booking): self
    {
        $this->url_booking = $url_booking;

        return $this;
    }

    public function getIdHotel(): ?Etablissement
    {
        return $this->id_hotel;
    }

    public function setIdHotel(?Etablissement $id_hotel): self
    {
        $this->id_hotel = $id_hotel;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getSlug(): ?string
    {
        return $this->slug;
    }

    public function setSlug(string $slug): self
    {
        $this->slug = $slug;

        return $this;
    }

    public function getPhotoPrincipale(): ?string
    {
        return $this->photo_principale;
    }

    public function setPhotoPrincipale(string $photo_principale): self
    {
        $this->photo_principale = $photo_principale;

        return $this;
    }

    public function getPhotoDeux(): ?string
    {
        return $this->photo_deux;
    }

    public function setPhotoDeux(string $photo_deux): self
    {
        $this->photo_deux = $photo_deux;

        return $this;
    }

    public function getPhoto3(): ?string
    {
        return $this->photo_3;
    }

    public function setPhoto3(string $photo_3): self
    {
        $this->photo_3 = $photo_3;

        return $this;
    }

    public function getDescriptionIntro(): ?string
    {
        return $this->description_intro;
    }

    public function setDescriptionIntro(string $description_intro): self
    {
        $this->description_intro = $description_intro;

        return $this;
    }
}

src/Controller/HotelController.php
<?php

namespace App\Controller;

use App\Entity\Etablissement;
use App\Entity\Suite;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

class HotelController extends AbstractController
{

    private $entityManager;

    public function __construct(EntityManagerInterface $entityManager)
    {
        $this->entityManager = $entityManager;
    }

    #[Route('/hotel/{slug}', name: 'app_hotel')]
    public function index($slug): Response
    {
        $etablissement = $this->entityManager->getRepository(Etablissement::class)->findOneBySlug($slug);
        $suites = $this->entityManager->getRepository(Suite::class)->findAll();

        if(!$etablissement) {
            return $this->redirectToRoute('app_home');
        }
        return $this->render('hotel/index.html.twig', [
            'etablissement' => $etablissement,
            'suites' => $suites
        ]);
    }

    #[Route('/hotel/{slug}/{nom_suite}', name: 'app_suite')]
    public function show($slug, $nom_suite): Response
    {
        $suite = $this->entityManager->getRepository(Suite::class)->findOneBySlug($nom_suite);
        $etablissement = $this->entityManager->getRepository(Etablissement::class)->findOneBySlug($slug);

        if(!$suite) {
            return $this->redirectToRoute('app_home');
        }
        return $this->render('hotel/suite.html.twig', [
            'suite' => $suite,
            'etablissement' => $etablissement
        ]);
    }
}

templates/hotel/index.html.twig
{% extends 'base.html.twig' %}

{% block body %}

    <!--=================================================-->
    <!--==========| H E A D E R |========================-->
    <!--=================================================-->

    <header class="header-hotel">
        <div class="hotel">
            <img class="hotel-picture" src="/uploads/files/{{ etablissement.photo }}">

            <div class="hotel-information">
                <h1 class="hotel-name">{{ etablissement.nom }}</h1>
                <h2 class="hotel-location">{{ etablissement.ville }}</h2>
            </div>

        </div>
    </header>

    <!--=================================================-->
    <!--==========| P R E S E N T A T I O N |============-->
    <!--=================================================-->

    <section class="presentation-section">

        <div class="container-fluid presentation-container">
            <div class="row presentation-row">
                <div class="col-md-6 presentation-main">
                    <h2 class="presentation-title">{{ etablissement.nom }}</h2>
                </div>
                <div class="col-md-6 presentation-texts">
                    <p class="presenation-text">Notre promesse dans tout les hotel Hypnos est de vous offrir
                        un instant, un moment, en dehors du temps ou vous pourrez oublié jusqu'au plus petit de vos
                        soucis. <br>
                        Les plus belles chambres, les plus beau hotel, les plus beau lieux, pour vous retrouvez avec
                        qui vous voulez, on est loin du mac do, mais venez comme vous êtes, on se charge du reste<p>
                </div>
            </div>
        </div>

    </section>

    <!--=================================================-->
    <!--==========| S E P A R A T O R |==================-->
    <!--=================================================-->

    <section class="section-separator-home">

        <div class="separator-home">
            <p class="separator-home-text">Les Suites</p>
        </div>
    </section>

    <!--=================================================-->
    <!--==========| S U I T E S |========================-->
    <!--=================================================-->

    <div class="container-fluid suites-container">
        {%  for suite in suites %}
            {% if etablissement.nom == suite.idHotel %}
            <div class="row suite-row">
                <div class="col-sm-6 suite-picture-div">
                    <img class="suite-picture-small" src="/uploads/files/{{ suite.photoPrincipale }}">
                </div>
                <div class="col-sm-6 suite-description-div">
                    <div class="test">
                        <h2 class="suite-name-small">{{ suite.nom }}</h2>
                        <p class="suite-descriptionSmall-small">{{ suite.descriptionIntro }}</p>
                        <p class="suite-description-small">{{ suite.description }}</p>
                    </div>
                    <a href="{{ path('app_suite',{'slug' : etablissement.slug, 'nom_suite' : suite.slug } ) }}">
                        <div class="suite-button-plus">
                            <span class="suite-button-text">En Savoir Plus</span>
                        </div>
                    </a>
                </div>
                <div class="separator-home"></div>
            </div>
            {% endif %}
        {% endfor %}
    </div>


{% endblock %}

{% block contact %}{% endblock %}

templates/hotel/suite.html.twig
{% extends 'base.html.twig' %}

{% block body %}
    <!--=================================================-->
    <!--==========| H E A D E R |========================-->
    <!--=================================================-->

    <header class="header-suite">
        <div class="suite">
            <img class="suite-picture" src="/uploads/files/{{ suite.photoPrincipale }}">

            <div class="suite-information">
                <h1 class="suite-name">{{ suite.nom }}</h1>
            </div>
        </div>
    </header>

    <!--=================================================-->
    <!--==========| P R E S E N T A T I O N |============-->
    <!--=================================================-->

    <section class="presentation-section">

        <div class="container-fluid presentation-container">
            <div class="row presentation-row">
                <div class="col-md-6 presentation-main">
                    <h2 class="suite-title">La suite {{ suite.nom }}</h2>
                    <h2 class="suite-price">{{ (suite.prix/100) }} € par nuit</h2>
                </div>
                <div class="col-md-6 presentation-texts">
                    <p class="presenation-text">Notre promesse dans tout les hotel Hypnos est de vous offrir
                        un instant, un moment, en dehors du temps ou vous pourrez oublié jusqu'au plus petit de vos
                        soucis. <br>
                        Les plus belles chambres, les plus beau hotel, les plus beau lieux, pour vous retrouvez avec
                        qui vous voulez, on est loin du mac do, mais venez comme vous êtes, on se charge du reste<p>
                </div>
            </div>
        </div>

    </section>

    <!--=================================================-->
    <!--==========| S E P A R A T O R |==================-->
    <!--=================================================-->

    <section class="section-separator-home">
        <div class="separator-home">
        </div>
    </section>

    <!--=================================================-->
    <!--==========| G A L L E R Y |======================-->
    <!--=================================================-->

    <section class="gallery-section">

        <div class="pics-gallery">
            <img class="suite-pic" src="/uploads/files/{{ suite.photoPrincipale }}">
            <img class="suite-pic" src="/uploads/files/{{ suite.photoDeux }}">
            <img class="suite-pic" src="/uploads/files/{{ suite.photo3 }}">
        </div>

    </section>

    <!--=================================================-->
    <!--==========| S E P A R A T O R |==================-->
    <!--=================================================-->

    <section class="section-separator-home">
        <div class="separator-home">
        </div>
    </section>

    <!--=================================================-->
    <!--==========| R E S E R V A T I O N |==============-->
    <!--=================================================-->

    <section class="reservation-section">


        <div class="container-fluid button-container">

            <div class="row button-row">

                <div class="col-md-4 button-col">
                    <div class="button button-resa-us">
                        <h2 class="button-text">reservez avec nous</h2>
                    </div>
                </div>

                <div class="col-md-4 button-col">
                    <div class="button button-resa-booking">
                        <h2 class="button-text">reservez sur Booking</h2>
                    </div>
                </div>

                <div class="col-md-4 button-col">

                            <a href="{{ path('app_hotel',{'slug' : etablissement.slug } ) }}">
                                <div class="button back-to-button">
                                    <h2 class="button-text">retour hotel {{ etablissement.nom }}</h2>
                                </div>
                            </a>

                </div>

            </div>

        </div>

    </section>


{% endblock %}